### ISSUE TITLE
Computing the matter bispectrum?

### ISSUE THREAD

**Issue by desh1701** [coccoinomane/song#11]
Hi,

I'm attempting to use SONG to compute the CDM density fluctuation
bispectrum, however, I cannot understand if and how it is output.
Currently, I am attempting to use the supplied matter.ini file, but I
don't think the resulting 'pertubations' files contain the information I
need, which is the value of the bispectrum at given ks.

Is it possible to compute this bispectrum in such a way that its output
resembles how CLASS outputs the power spectrum, i.e., with the value of
the bispectrum given at a range of k1,k2,k3s?

Thanks for your help.

**Comment by coccoinomane** [comment]
Hi @desh1701 !

I have updated the readme with further information on how to extract the cold dark matter density bispectrum, please have a look; hopefully the procedure will be clearer 😊

Please let me know if you need further help.

Cheers,
Guido

**Comment by desh1701** [comment]
Hi Guido,

Thanks a lot for the quick response, the updated readme makes it much clearer how to get the information I need out.

**Comment by coccoinomane** [comment]
Hey @desh1701 ,

I have realized that I didn't explain how to extract the bispectrum as a function of (k1,k2,k3), which is probably what you were looking for ;-)

I've done so now (75d38aa332679117c260ccb7fd37303dd5e16b6e), please have a look at the "3D Slices" section of the README.

I have also added further information on how to extract the data from the binary files, and explained more accurately how `k1_out`, `k2_out`, `k3_out`, `tau_out` and `z_out` work.

Feel free to use the Github issues to ask more questions or to suggest improvementes.

Cheers,
Guido

**Comment by desh1701** [comment]
Hi @coccoinomane ,

Thanks for the further clarification, that simplifies things for me greatly.
